# Generated by Django 4.1.5 on 2023-02-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_firstname_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
    ]
